[workspace]
channels = ["knime/label/nightly", "knime", "conda-forge", "dglteam"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[tasks]

[dependencies]
python = "*"
knime-extension = "5.12.*"
knime-python-base = "5.12.*"
knime-python-versions = "5.12.*"
tokenizers = ">=0.20.1"
transformers = ">=4.45.2"
pytorch-cpu = ">=2.7.0,<3"
scikit-learn = ">=1.7.2"


[feature.build.dependencies]
python = "*"
knime-extension-bundling = "5.12.*"

[feature.build.tasks]
build = { args = [{ "arg" = "dest", "default" = "./local-update-site" }], cmd = "build_python_extension.py . {{ dest }} --update-sites-version 5.12"}

[environments]
build = {features = ["build"], no-default-feature = true}
